In [7]:
import requests
import pandas as pd

In [8]:
response = requests.get("https://stephen-king-api.onrender.com/api/books")

In [9]:
data = response.json()

In [11]:
df = pd.json_normalize(data["data"])
df = df[["id","Title","Year","ISBN"]]
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [12]:
cats_breeds_response = requests.get("https://catfact.ninja/breeds")

cats_breeds_data = cats_breeds_response.json()

df = pd.json_normalize(cats_breeds_data["data"])

df

,breed,country,origin,coat,pattern
0,Abyssinian,Ethiopia,Natural/Standard,Short,Ticked
1,Aegean,Greece,Natural/Standard,Semi-long,Bi- or tri-colored
2,American Curl,United States,Mutation,Short/Long,All
3,American Bobtail,United States,Mutation,Short/Long,All
4,American Shorthair,United States,Natural,Short,All but colorpoint
5,American Wirehair,United States,Mutation,Rex,All but colorpoint
6,Arabian Mau,Arabian Peninsula,Natural,Short,
7,Australian Mist,Australia,Crossbreed,Short,Spotted and Classic tabby
8,Asian,developed in the United Kingdom (founding stoc...,,Short,Evenly solid
9,Asian Semi-longhair,United Kingdom,Crossbreed,Semi-long,Solid
10,Balinese,developed in the United States (founding stock...,Crossbreed,Long,Colorpoint
11,Bambino,United States,Crossbreed,Hairless/Furry down,
12,Bengal,developed in the United States (founding stock...,Hybrid,Short,Spotted/Marbled
13,Birman,developed in France (founding stock from Burma),Natural,Semi Long,Colorpoint
14,Bombay,developed in the United States (founding stock...,Crossbred,Short,Solid
15,Brazilian Shorthair,Brazil,Natural,Short,All
16,British Semi-longhair,United Kingdom,,Medium,All
17,British Shorthair,United Kingdom,Natural,Short,All
18,British Longhair,United Kingdom,,Long,
19,Burmese,Burma and Thailand,Natural,Short,Solid
20,Burmilla,United Kingdom,Crossbreed,Short/Long,
21,California Spangled,United States,Crossbreed,Short,Spotted
22,Chantilly-Tiffany,United States,,,
23,Chartreux,France,Natural,Short,Solid
24,Chausie,France,Hybrid,Short,Ticked